GET http://localhost:8080/rest/hello
Authorization: Token eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0amxlZSIsInVzZXJJZCI6MTAsInJvbGUiOiJVU0VSIn0.gQ1k7nMa44_3rM4EFtGOpQmWba3uU6_ZCdWx6QzqSa8QZfD67YFG5oUjpJk-uwaCO6n8AVqU0ooUsPff7qmWjw

###


# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);